# Generated by Django 3.1.5 on 2021-05-01 15:50

from django.db import migrations, models
import django.db.models.deletion
import team.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', team.fields.UpperCaseField(max_length=45, verbose_name='Nome')),
                ('initials', team.fields.UpperCaseField(max_length=3, verbose_name='Sigla')),
                ('start_year', models.PositiveIntegerField(verbose_name='Ano de Fundação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset', verbose_name='Foto')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coach', verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrção')),
                ('date', models.DateField(verbose_name='Data do Treino')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('players', models.ManyToManyField(to='accounts.Player', verbose_name='Jogadores')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team', verbose_name='Treino')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.PositiveIntegerField(choices=[(1, 'goalkeeper_titular'), (2, 'fixed_titular'), (3, 'left_wing_titular'), (4, 'right_wing_titular'), (5, 'pivot_titular'), (6, 'selected'), (7, 'unselected')], verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.player', verbose_name='Jogador')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team', verbose_name='Time')),
            ],
        ),
    ]
