# Generated by Django 3.1.5 on 2021-05-01 15:50

import accounts.fields
import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='E-mail')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Nome de Usuário')),
                ('first_name', accounts.fields.UpperCaseField(max_length=30, verbose_name='Nome')),
                ('last_name', accounts.fields.UpperCaseField(max_length=60, verbose_name='Sobrenome')),
                ('birthday', models.DateField(verbose_name='Data de Nascimento')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'coach'), (2, 'player')], verbose_name='Papel de Usuário')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('password', accounts.fields.PasswordField(max_length=128, verbose_name='Senha')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Equipe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.asset', verbose_name='Foto de Perfil')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('position', models.PositiveSmallIntegerField(choices=[(1, 'goalkeeper'), (2, 'fixed'), (3, 'wing'), (4, 'pivot')], verbose_name='Posição em Quadra')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura em metros')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso em quilogramas')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Idade em anos')),
                ('uniform_size', models.PositiveSmallIntegerField(choices=[(1, 'PP'), (2, 'P'), (3, 'M'), (4, 'G'), (5, 'GG')], verbose_name='Tamanho do Uniforme')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalkeeper', accounts.fields.IntegerRangeField(default=50)),
                ('fixed', accounts.fields.IntegerRangeField(default=50)),
                ('wing', accounts.fields.IntegerRangeField(default=50)),
                ('pivot', accounts.fields.IntegerRangeField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.player', verbose_name='Jogador')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
            },
        ),
    ]
